- hosts: local
  connection: local
  vars_files:
    - vars.yml
  tasks:
    - name: create namespace
      k8s:
        name: "{{namespace_name}}"
        api_version: v1
        kind: Namespace
        state: present